### PR TITLE
 - pump require yubico/u2flib-server to 1.0.1.

### PR DESCRIPTION
**Pull request by chakphanu**
- replace resources/js/u2f.js from https://demo.yubico.com/js/u2f-api.js.
 - update resources/js/app.js to supoport new u2f.js from yubico.

### CODE REVIEW

**Comment by lahaxearnaud** [comment]
Is there any breaking changes ?

**Comment by lahaxearnaud** [comment]
The yubico/u2flib-server version is not available on PHP 5.4 and 5.5 but it's not a bad thing. It's time to drop support of those versions

**Comment by chakphanu** [comment]
I'm tested pass with Laravel 5.6. and PHP 7.2.1.
new U2F.js can fix "The visited URL doesn’t match the App ID or your are
tot using HTTPS" on Chrome@Android.
Before change u2f.js, i'm cannot use Chrome@Android.

**Comment by lahaxearnaud** [comment]
Ok. Thanks for the PR.

**Pull request merged**
